### PR TITLE
no need to call if esindexer not config

### PR DESCRIPTION
**Pull request by utas-raymondng**

### CODE REVIEW

**Comment by vietnguyengit** [comment]
I commented out stuff related to the indexer in .env

```dotenv
#INDEXER_HOST=localhost
#INDEXER_PORT=8081
#INDEXER_APIKEY=Q*z6OfL^4u^1nMhH
```

and also in `application.properties`

```yaml
#aodn.geonetwork4.esIndexer.host=${INDEXER_HOST:http://localhost}
aodn.geonetwork4.esIndexer.port=${INDEXER_PORT:80}
aodn.geonetwork4.esIndexer.apikey=${INDEXER_APIKEY}
#aodn.geonetwork4.esIndexer.urlIndex=${aodn.geonetwork4.esIndexer.host}:${aodn.geonetwork4.esIndexer.port}/api/v1/indexer/index/{uuid}
```

then I run the geonetwork4, cannot hit this line

```java
logger.warn("Call to es-indexer is off due to config missing");
```

and when I tried to create a dummy record to see if the indexer still be called

```console
geonetwork4   | 2024-07-08T11:13:27,382 INFO  [au.org.aodn.geonetwork4.handler.GenericEntityListener] - Call indexer on metadata 4613001f-3590-4d9d-a69e-4231da1487cc after metadata updated.
geonetwork4   | 2024-07-08T11:13:27,383 INFO  [au.org.aodn.geonetwork4.handler.GenericEntityListener] - Call indexer update http://localhost:8080/api/v1/indexer/index/{uuid} metadata 4613001f-3590-4d9d-a69e-4231da1487cc
geonetwork4   | 2024-07-08T11:13:27,426 ERROR [au.org.aodn.geonetwork4.handler.GenericEntityListener] - Fail to call indexer on metadata 4613001f-3590-4d9d-a69e-4231da1487cc after transaction committed. 404 Not Found: "{<EOL>"message":"Not Found",<EOL>"url":"/api/v1/indexer/index/4613001f-3590-4d9d-a69e-4231da1487cc",<EOL>"status":"404"<EOL>}"
```

looks like `urlIndex` still stuck somewhere in my environment, where should I look for @utas-raymondng ?

**Comment by vietnguyengit** [comment]
I used the script you prepared:

image

**Comment by utas-raymondng** [comment]
> I used the script you prepared:
> 
> image

sorry my bad bug there let me fix it

**Comment by vietnguyengit** [comment]
no problem

**Comment by utas-raymondng** [comment]
Comment INDEXER_HOST: ${INDEXER_HOST:-http://localhost} in the docker-gn-compose.yml should work now

**Review by vietnguyengit — APPROVED** [review]
LGTM

```console
geonetwork4   | 2024-07-08T14:30:33,216 WARN  [au.org.aodn.geonetwork4.handler.GenericEntityListener] - Call to es-indexer is off due to config missing
```

**Pull request merged**
